name: Deploy branch

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "onlinemat-${GITHUB_REF#refs/heads/}" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: ${GITHUB_REF#refs/heads/}
          buildpack: "https://github.com/mars/create-react-app-buildpack.git"